{{- if .Values.monitoring.enabled }}
{{- if eq .Values.monitoring.kind "prometheus" }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ template "allure-testops.gateway.fullname" . }}-monitor
  labels:
    app: {{ template "allure-testops.gateway.fullname" . }}
spec:
  selector:
    matchLabels:
      app: {{ template "allure-testops.gateway.fullname" . }}
      version: v1
  endpoints:
    - port: http
      path: "/management/prometheus"
      interval: {{ .Values.monitoring.interval}}
      honorLabels: true

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ template "allure-testops.uaa.fullname" . }}-monitor
  labels:
    app: {{ template "allure-testops.uaa.fullname" . }}
spec:
  selector:
    matchLabels:
      app: {{ template "allure-testops.uaa.fullname" . }}
      version: v1
  endpoints:
    - port: http
      path: "{{ .Values.allure.uaaContextPath }}management/prometheus"
      interval: {{ .Values.monitoring.interval}}
      honorLabels: true

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ template "allure-testops.report.fullname" . }}-monitor
  labels:
    app: {{ template "allure-testops.report.fullname" . }}
spec:
  selector:
    matchLabels:
      app: {{ template "allure-testops.report.fullname" . }}
      version: v1
  endpoints:
    - port: http
      path: "{{ .Values.allure.reportContextPath }}management/prometheus"
      interval: {{ .Values.monitoring.interval}}
      honorLabels: true
{{- else if eq .Values.monitoring.kind "victoria" }}
---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: testops-gateway
spec:
  namespaceSelector:
    any: false
  selector:
    matchLabels:
      app: {{ template "allure-testops.gateway.fullname" . }}
  endpoints:
    - path: /management/prometheus
      interval: {{ .Values.monitoring.interval}}
      port: http
      metricRelabelConfigs:
        - action: drop
          regex: lettuce_command_(completion_seconds_bucket|firstresponse_seconds_bucket|completion_seconds)
          sourceLabels:
            - __name__

---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: testops-uaa
spec:
  namespaceSelector:
    any: false
  selector:
    matchLabels:
      app: {{ template "allure-testops.uaa.fullname" . }}
  endpoints:
    - path: "{{ .Values.allure.uaaContextPath }}management/prometheus"
      interval: {{ .Values.monitoring.interval}}
      port: http

---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: testops-report
spec:
  namespaceSelector:
    any: false
  selector:
    matchLabels:
      app: {{ template "allure-testops.report.fullname" . }}
  endpoints:
    - path: "{{ .Values.allure.reportContextPath }}management/prometheus"
      interval: {{ .Values.monitoring.interval}}
      port: http

{{- end }}
{{- end }}
