{{- if .Values.rbac.enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-{{ template "allure-testops.fullname" . }}
  labels:
    app: {{ template "allure-testops.fullname" . }}
    chart: {{ template "allure-testops.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
{{- if .Values.aws.enabled }}
  annotations:
    eks.amazonaws.com/role-arn: "{{ .Values.aws.arn }}"
{{- end }}
{{- end -}}
